SENDER_PORT = 8888
RECEIVER_PORT = 8889
HEADER_SIZE = 7
CHANNEL_RELIABLE = 0
CHANNEL_UNRELIABLE = 1
CHANNEL_ACK = 2  # ACK packet type
RETRANSMIT_TIMEOUT = 0.2  # 200ms
MAX_RETRANSMITS = 3  # Maximum retry attempts
REORDER_BUFFER_SIZE = 100  # Max out-of-order packets to buffer
REORDER_TIMEOUT = 0.2  # 200ms - Skip missing packet after this threshold (t from spec) 